### ISSUE TITLE
安装JimV-C,启动服务报错：

### ISSUE THREAD

**Issue by zhanghonged** [jamesiter/JimV-C#6]
[2018-05-19 14:26:17 +0000] [27156] [INFO] Worker exiting (pid: 27156)
[2018-05-19 14:26:17 +0000] [27161] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/venv/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/www/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/www/sites/JimV-C/main.py", line 16, in <module>
    from flask.ext.session import Session
  File "/home/www/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named ext.session

**Comment by zhanghonged** [comment]
已解决：
/home/www/sites/JimV-C/main.py
from flask.ext.session import Session修改为
from flask_session import Session

**Comment by jamesiter** [comment]
https://github.com/jamesiter/JimV-C/commit/9fd8ae6d92342f4479797ee6c8ea8e72f4f8e0d8#diff-5bc02cefb3ea9e27f1a6776eabd1935d
![image](https://user-images.githubusercontent.com/2541839/42128526-327d552c-7ce0-11e8-9400-09de18c636a0.png)
